name: 3 Barnes Street Oast
favicon: null
layout_spectrum: 0.6904653066303581
typography_spectrum: 0.47170805442146957
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  brandStrength: 0.4727458057459444
  lightness: 0.45454513537697494
  saturation: 0.5595859824679792
  rhythmicContrast: 0.45289984019473195
purpose: []
